services:
  backend:    
    build:
     context: .
     dockerfile: NotificationMicroservice/Dockerfile
    restart: always
    ports:
      - "3000:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: local_pgdb_notif
    restart: always
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata:
  pgadmin-data: