// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationMicroservice.DataAccess;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationMicroservice.DataAccess.Migrations
{
    [DbContext(typeof(NotificationMicroserviceDbContext))]
    [Migration("20240719073609_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationMicroservice.DataAccess.Entities.MessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TypesId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TypesId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("NotificationMicroservice.DataAccess.Entities.TemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifyUserName")
                        .HasColumnType("text");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TypesId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TypesId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("NotificationMicroservice.DataAccess.Entities.TypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifyUserName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("NotificationMicroservice.DataAccess.Entities.MessageEntity", b =>
                {
                    b.HasOne("NotificationMicroservice.DataAccess.Entities.TypeEntity", "Types")
                        .WithMany("Messages")
                        .HasForeignKey("TypesId");

                    b.Navigation("Types");
                });

            modelBuilder.Entity("NotificationMicroservice.DataAccess.Entities.TemplateEntity", b =>
                {
                    b.HasOne("NotificationMicroservice.DataAccess.Entities.TypeEntity", "Types")
                        .WithMany("Templates")
                        .HasForeignKey("TypesId");

                    b.Navigation("Types");
                });

            modelBuilder.Entity("NotificationMicroservice.DataAccess.Entities.TypeEntity", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Templates");
                });
#pragma warning restore 612, 618
        }
    }
}
